using EphemerisMapper.Model.Attributes;

namespace EphemerisMapper.Model.Enums;

public enum StarEnum
{
    [TraditionalLord(PlanetEnum.Ketu)]
    Aswini,
    [TraditionalLord(PlanetEnum.Ketu)]
    Bharani,
    [TraditionalLord(PlanetEnum.Ketu)]
    Krittika,
    [TraditionalLord(PlanetEnum.Ketu)]
    Rohini,
    [TraditionalLord(PlanetEnum.Ketu)]
    Mrigashira,
    [TraditionalLord(PlanetEnum.Ketu)]
    Adra,
    [TraditionalLord(PlanetEnum.Ketu)]
    Punarvasu,
    [TraditionalLord(PlanetEnum.Ketu)]
    Pushya,
    [TraditionalLord(PlanetEnum.Ketu)]
    Aslesha,
    [TraditionalLord(PlanetEnum.Ketu)]
    Magha,
    [TraditionalLord(PlanetEnum.Ketu)]
    PurvaPhalguni,
    [TraditionalLord(PlanetEnum.Ketu)]
    UttaraPhalguni,
    [TraditionalLord(PlanetEnum.Ketu)]
    Hasta,
    [TraditionalLord(PlanetEnum.Ketu)]
    Chitra,
    [TraditionalLord(PlanetEnum.Ketu)]
    Swati,
    [TraditionalLord(PlanetEnum.Ketu)]
    Vishaka,
    [TraditionalLord(PlanetEnum.Ketu)]
    Anuradha,
    [TraditionalLord(PlanetEnum.Ketu)]
    Jyestha,
    [TraditionalLord(PlanetEnum.Ketu)]
    Mula,
    [TraditionalLord(PlanetEnum.Ketu)]
    PurvaAshadha,
    [TraditionalLord(PlanetEnum.Ketu)]
    UttaraAshadha,
    [TraditionalLord(PlanetEnum.Ketu)]
    Sravana,
    [TraditionalLord(PlanetEnum.Ketu)]
    Dhanishta,
    [TraditionalLord(PlanetEnum.Ketu)]
    Shatabhisha,
    [TraditionalLord(PlanetEnum.Ketu)]
    PurvaBhadrapada,
    [TraditionalLord(PlanetEnum.Ketu)]
    UttaraBhadrapada,
    [TraditionalLord(PlanetEnum.Ketu)]
    Revati,
}